services:
  central:
    image: federared-system_image:latest
    build: .
    container_name: federated_central
    command: ["python", "main.py", "true", "0.0.0.0:8765", "0.0.0.0:8765"]
    ports:
      - "8765:8765"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  node1:
    image: federared-system_image:latest
    build: .
    container_name: federated_node1
    command: ["python", "main.py", "false", "node1:8766", "central:8765"]
    depends_on:
      - central
    volumes:
      - ./data/Hospital_1.csv:/app/data/Hospital.csv:ro
    environment:
      - PYTHONUNBUFFERED=1

  node2:
    image: federared-system_image:latest
    build: .
    container_name: federated_node2
    command: ["python", "main.py", "false", "node2:8767", "central:8765"]
    depends_on:
      - central
    volumes:
      - ./data/Hospital_2.csv:/app/data/Hospital.csv:ro
    environment:
      - PYTHONUNBUFFERED=1

  node3:
    image: federared-system_image:latest
    build: .
    container_name: federated_node3
    command: ["python", "main.py", "false", "node3:8768", "central:8765"]
    depends_on:
      - central
    volumes:
      - ./data/Hospital_3.csv:/app/data/Hospital.csv:ro
    environment:
      - PYTHONUNBUFFERED=1
